version: "3.8"

services:
  postgres:
    image: postgres:16-bullseye
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./CREATE_1.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
  sso-service:
    depends_on:
        - postgres
    build:
      context: ./sso-service
    container_name: sso-service
    volumes:
      - .:/sso-service
    ports:
      - 8080:80
    command: ["/main"]

volumes:
  postgres_data: